
import localFont from "next/font/local";
import "./globals.css";
import Name  from "@/Helper/Context";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body>
       <Name>{children}</Name>
      </body>
    </html>
  );
}
